name: Supabase Database Migration and Functions Deployment

on:
  push:
    branches:
      - main
      - staging
    paths:
      - 'supabase/migrations/**'
      - 'supabase/functions/**'
      - '.github/workflows/supabase-migration.yml'

env:
  SUPABASE_PROJECT_ID_STAGING: ${{ secrets.SUPABASE_PROJECT_ID_STAGING }}
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  SUPABASE_PROJECT_ID_PROD: ${{ secrets.SUPABASE_PROJECT_ID_PROD }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Login to Supabase
        run: supabase login --access-token ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        run: |
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID_STAGING }}
          supabase db push
          supabase functions deploy --project-ref ${{ secrets.SUPABASE_PROJECT_ID_STAGING }}

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID_PROD }}
          supabase db push
          supabase functions deploy --project-ref ${{ secrets.SUPABASE_PROJECT_ID_PROD }}

      - name: Generate and commit types
        run: |
          supabase gen types typescript --project-id ${{ github.ref == 'refs/heads/main' && secrets.SUPABASE_PROJECT_ID_PROD || secrets.SUPABASE_PROJECT_ID_STAGING }} > src/lib/supabase/types.ts
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add src/lib/supabase/types.ts
          git commit -m "chore: update supabase types" || true
          git push || true 